name: surf_lint_rules
version: 1.4.1
description: Lint rules for "Surf" company for Dart and Flutter projects.
repository: "https://github.com/surfstudio/flutter-surf-lint-rules"
issue_tracker: "https://github.com/surfstudio/flutter-surf-lint-rules/issues"

dependencies:
  dart_code_metrics: ^4.0.0-dev.2
  flutter_lints: ^1.0.3

environment:
  sdk: ">=2.13.0 <3.0.0"
